### PR TITLE
[426] Accessibility for sign up view

### PR DESCRIPTION
**Pull request by hmarcks**
# 💅🏼 What issue does this fix?
#426 
Fixes a few accessibility issues:
• Missing two input labels
• Landmark / markup structure issues
• Error text color lacks sufficient contrast
• Language toggle missing focus state

## 🍂 Before You Submit

* [ ] Did you write tests?
* [x] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Did you run `bundle exec rspec` from the root?
* [ ] Did you run `bundle exec rails rswag` from the root?
* [ ] Did you run `bundle exec rubocop` from the root?
* [x] Did you run `yarn lint` in `/client`?
* [x] Did you run `yarn test` in `/client`?
* [ ] Are your primary keys UUIDs on any new tables?

## 🏺 Accessibility
Ran tests and did some manual testing.

## 🛷 Deployment
NA

## 🧵 Steps to set up locally
NA

## 🧳 Steps to test
Go to the sign up view and run [axe](https://www.deque.com/axe/) or [Lighthouse](https://developers.google.com/web/tools/lighthouse)

## 🕯 Caveats, concerns
There will be some ARIA issues flagged by the tests, but I imagine it would be very hard to untangle from the Ant components (I'm not qualified). There are also three color contrast issues that are flagged - two are false and one is for a non-essential element that would require some css overrides of the Ant styles, so I left it for now.

### CODE REVIEW

**Review by katelovescode — APPROVED** [review]
This looks great!  Make sure you add QA instructions to the original ticket for Chelsea, and then after you merge, move the ticket into QA on the project board.

**Comment by hmarcks** [comment]
Thanks @katelovescode , I updated the original ticket. Before I rebased, I saw this message that blocked me from merging:

Screen Shot 2020-10-14 at 12 01 04 PM

It is now rebased so requires a review again, then I image I'll see the above blocker again.

**Review by katelovescode — APPROVED** [review]
Try again, now that I've reapproved you should be able to merge!

**Comment by hmarcks** [comment]
🤔  still getting this message: The base branch restricts merging to authorized users. [Learn more about protected branches.](https://docs.github.com/articles/about-protected-branches/)

**Pull request merged**
