### PR TITLE
511/add table column and tweaks

### PR DESCRIPTION
**Pull request by cjhaddad**
…itles, fix styling issues

#511 and #428  💅🏼 What issue does this fix?

## 🍂 Before You Submit

* [ ] Did you write tests?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Did you run `bundle exec rspec` from the root?
* [ ] Did you run `bundle exec rails rswag` from the root?
* [ ] Did you run `bundle exec rubocop` from the root?
* [ ] Did you run `yarn lint` in `/client`?
* [ ] Did you run `yarn test` in `/client`?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Data Migrations
* [ ] Schema Migrations
* [ ] Dependencies

### CODE REVIEW

**Comment by katelovescode** [comment]
Looks great!  Note to @csprayregen during QA - the gray doesn't extend to the bottom of the page but that's already logged in #218

**Review by katelovescode — APPROVED** [review]

**Review by katelovescode — CHANGES_REQUESTED** [review]
Oh no!  Just noticed - the potential revenue column should be between the other two, not at the end.  https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2572%3A15126

**Comment by cjhaddad** [comment]
> Oh no! Just noticed - the potential revenue column should be between the other two, not at the end. https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2572%3A15126

@katelovescode it should be between min and max? the figma shows two different dashboard versions. I also see 'guaranteed revenue' -- should I add that too? cc: @csprayregen

**Comment by csprayregen** [comment]
Hey @cjhaddad and @katelovescode sorry for confusion on this. Yes, let's put potential between min and max.

**Comment by cjhaddad** [comment]
ok! potential revenue moved to be between min and max columns @katelovescode and @csprayregen. going to merge.

**Pull request merged**
