### PR TITLE
PIE-1643 payments index default filter

### LINKED ISSUE #1643: The existence of a payment for the requested month is returned in an API call to the backend
## ✨ What new feature do you want to see?

The API needs to accommodate viewing child payments for a particular month

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria

- [x] Blocked by #1644 and #1642 
- [ ] An index GET request is built in the controller that will return all the payments a user has access to
- [ ] A PaymentPolicy is built to restrict which payments users can see by permissions
- [ ] A PaymentBlueprint is built to accommodate a filter_date and return the correct payments for the requested month
- [ ] A route is created for that controller method
- [ ] The appropriate request specs are created and pass

### PR DESCRIPTION
**Pull request by dragonbone81**
## 💅🏼 What issue does this fix?
closes #1643 

Added in a default filter for current month

### CODE REVIEW

**Comment by dragonbone81** [comment]
Linting seems to be failing, but the code it's referencing doesn't exist the way its saying it does...
for example `{ where("EXTRACT(MONTH FROM month) = ?", month.month) }` has been changed but its still linting that

**Comment by katelovescode** [comment]
> Linting seems to be failing, but the code it's referencing doesn't exist the way its saying it does... for example `{ where("EXTRACT(MONTH FROM month) = ?", month.month) }` has been changed but its still linting that

Try running `bundle exec rubocop -a` locally - it will autocorrect anything it's safe to fix and maybe give you a little more insight into why a particular example is failing.  If you are still having issues after that, let me know and I can take a look!

**Comment by dragonbone81** [comment]
@katelovescode sweet thanks that worked :))

**Comment by katelovescode** [comment]
@dragonbone81 I'm going to force merge this and if we have to fix linting on the atlassian branch we'll do it there - sometimes CI has cacheing issues and we've fixed some of them on develop, I'll do some rebase magic or have @davidcandeau do it.

**Comment by katelovescode** [comment]
@dragonbone81 I did some rebasing; I think we had a bad merge in there, but it *should* be fixed now.  Can you review the files changed to make sure I didn't miss any functionality changes you made?

**Review by katelovescode — APPROVED** [review]

**Comment by dragonbone81** [comment]
@katelovescode ok merged again looks good this time :) will merge the PR

**Comment by katelovescode** [comment]
@all-contributors please add @dragonbone81 for code, tests

**Pull request merged**
