### PR TITLE
428/dashboard table setup

### PR DESCRIPTION
**Pull request by cjhaddad**
#428  💅🏼 What issue does this fix?

## 🍂 Before You Submit

* [ ] Did you write tests?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Did you run `bundle exec rspec` from the root?
* [ ] Did you run `bundle exec rails rswag` from the root?
* [ ] Did you run `bundle exec rubocop` from the root?
* [ ] Did you run `yarn lint` in `/client`?
* [ ] Did you run `yarn test` in `/client`?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Data Migrations
* [ ] Schema Migrations
* [ ] Dependencies

## 🧳 Steps to test

Checkout /dashboard view

### CODE REVIEW

**Comment by katelovescode** [comment]
One thing I noticed in Figma; is there supposed to be a "selectable" row with blue background?  See this screenshot (and cc @rebeccakarasiktw )
Screen Shot 2020-10-28 at 8 39 59 PM

**Comment by rebeccakarasiktw** [comment]
> One thing I noticed in Figma; is there supposed to be a "selectable" row with blue background? See this screenshot (and cc @rebeccakarasiktw )
> Screen Shot 2020-10-28 at 8 39 59 PM

there should be two states (aside from the default)
- Selected (background gray 4)
- Hover (background blue 4)
The colors are here. https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=131%3A497

**Comment by cjhaddad** [comment]
will adjust row colors!

**Comment by katelovescode** [comment]
@csprayregen when this ends up in QA we decided to forego storing "selected" rows (gray in the mockup) in application state because right now nothing's selectable, seems like building future behavior that would confuse folks using the UI.  Per @rebeccakarasiktw:
> hey! there should be two states, 1 selected (gray) 1 hover (blue). but yeah you are totally right that there is nothing to select right now, so im not sure if it makes sense to include that style then :thinking_face:

**Review by katelovescode — APPROVED** [review]

**Pull request merged**
