### PR TITLE
Adds blueprints (serializers) for the dashboard

### PR DESCRIPTION
**Pull request by katelovescode**
# 💅🏼 What issue does this fix?
#526 - this uses the blueprinter gem for serializing the dashboard information in a way that makes sense.

## 🍂 Before You Submit

* [X] Did you write tests?
* [X] Did you run `bundle exec rspec` from the root?
* [X] Did you run `bundle exec rails rswag` from the root?
* [X] Did you run `bundle exec rubocop` from the root?

## 🛷 Deployment
* [X] Dependencies
  * `blueprinter` gem

## 🧵 Steps to set up locally

```
bundle install
```

## 🧳 Steps to test
* Using postman, log in as an existing user with children
* Using postman, hit the case_list_for_dashboard endpoint and you should see only current approval case numbers
* You can test this by adding an additional (expired) approval, hitting the endpoint again, and making sure you still only see one (the current) approval

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
Are you using the seeds.rb data?  When I run the queries in the console, they’re fine. (No duplicates).
What do you get without  `.uniq ?` 

I haven't used the Blueprinter gem, but quickly skimming their documentation, I wonder about this in ChildBlueprint:
```
  ...
  association :approvals, blueprint: ApprovalBlueprint, view: :dashboard do |child|
      child.approvals.current
    end
```
Doesn't this print every child for each approval (that is current)?  

(I’m having trouble with Postman.  I’ll ask about that later.  I think I need some hand-holding to get the JWT stuff really working.  I keep getting _‘Signature has expired’._)

**Comment by katelovescode** [comment]
> Are you using the seeds.rb data? When I run the queries in the console, they’re fine. (No duplicates).
> What do you get without `.uniq ?`

If you turn off uniq and then run the tests, they have too many records, and they're duplicates

> I haven't used the Blueprinter gem, but quickly skimming their documentation, I wonder about this in ChildBlueprint:
> 
> ```
>   ...
>   association :approvals, blueprint: ApprovalBlueprint, view: :dashboard do |child|
>       child.approvals.current
>     end
> ```
> 
> Doesn't this print every child for each approval (that is current)?

My understanding would be that this is the Blueprint for the child in question, which returns that child's approvals that are current.  Just as if I was in the console and typed `Child.first.approvals.current` - it should be scoped only to that child.  I think it's the query itself that's creating duplicates; the seeds might not have multiple approvals so they wouldn't turn up multiples?  Maybe?  I guess if something in my query or joined scopes is returning approvals instead of children, it'd make sense that there would be duplicates in the tests.

> (I’m having trouble with Postman. I’ll ask about that later. I think I need some hand-holding to get the JWT stuff really working. I keep getting _‘Signature has expired’._)

I'll be working this evening so we can work through this.  We have a postman collection, I'll try and add you to it this afternoon.

**Comment by weedySeaDragon** [comment]
Hm.  No duplicates for me, even without 'uniq':
1.  I ran rake db:seed:replant

Then, in the console:
```
>> user = User.find_by(full_name: 'Kate Donaldson')
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."full_name" = $1 LIMIT $2  [["full_name", "Kate Donaldson"], ["LIMIT", 1]]
=> #<User id: "6a757758-5182-4fcb-8945-0ae2867cdd78", active: true, full_name: "Kate Donaldson", greeting_name: "Kate", email: "test@test.com", language: "english", phone_type: "cell", opt_in_email: true, opt_in_text: true, phone_number: "8888888888", service_agreement_accepted: true, timezone: "Central Time (US & Canada)", created_at: "2020-11-11 19:58:07", updated_at: "2020-11-11 19:58:07", organization: "Pie for Providers", admin: false>

>> kids_active_current = Child.active.with_current_approval
  Child Load (1.7ms)  SELECT "children".* FROM "children" INNER JOIN "child_approvals" ON "child_approvals"."child_id" = "children"."id" INNER JOIN "approvals" ON "approvals"."id" = "child_approvals"."approval_id" WHERE "children"."active" = $1 AND (effective_on <= '2020-11-11' AND expires_on > '2020-11-11') LIMIT $2  [["active", true], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Child id: "1c05c610-09cf-4a52-b16e-af595db735a1", active: true, full_name: "Maria Baca", date_of_birth: "2012-03-21", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "1f715dd4-cc8f-4ea3-a099-eabf9e7914ed", active: true, full_name: "Marcus Smith", date_of_birth: "2013-07-29", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "454aa341-e5e2-441c-90d8-47bce4826c83", active: true, full_name: "Tarquinius Kelly", date_of_birth: "2018-09-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "5dab94a3-4bd8-46a8-b7f3-5255e614828e", active: true, full_name: "Sabina Akers", date_of_birth: "2014-08-02", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "b17c232e-9da5-499b-891c-56c5f8ee05b0", active: true, full_name: "K'Shawn Henderson", date_of_birth: "2013-05-05", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "f2895d9c-43e2-46c3-9d69-057492868511", active: true, full_name: "Mubiru Karstensen", date_of_birth: "2017-12-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">]>

>> kids_active_current.each{|kid| puts kid.inspect}
  Child Load (1.2ms)  SELECT "children".* FROM "children" INNER JOIN "child_approvals" ON "child_approvals"."child_id" = "children"."id" INNER JOIN "approvals" ON "approvals"."id" = "child_approvals"."approval_id" WHERE "children"."active" = $1 AND (effective_on <= '2020-11-11' AND expires_on > '2020-11-11')  [["active", true]]
#<Child id: "1c05c610-09cf-4a52-b16e-af595db735a1", active: true, full_name: "Maria Baca", date_of_birth: "2012-03-21", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "b17c232e-9da5-499b-891c-56c5f8ee05b0", active: true, full_name: "K'Shawn Henderson", date_of_birth: "2013-05-05", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "1f715dd4-cc8f-4ea3-a099-eabf9e7914ed", active: true, full_name: "Marcus Smith", date_of_birth: "2013-07-29", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "5dab94a3-4bd8-46a8-b7f3-5255e614828e", active: true, full_name: "Sabina Akers", date_of_birth: "2014-08-02", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "f2895d9c-43e2-46c3-9d69-057492868511", active: true, full_name: "Mubiru Karstensen", date_of_birth: "2017-12-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "454aa341-e5e2-441c-90d8-47bce4826c83", active: true, full_name: "Tarquinius Kelly", date_of_birth: "2018-09-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
=> [#<Child id: "1c05c610-09cf-4a52-b16e-af595db735a1", active: true, full_name: "Maria Baca", date_of_birth: "2012-03-21", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "b17c232e-9da5-499b-891c-56c5f8ee05b0", active: true, full_name: "K'Shawn Henderson", date_of_birth: "2013-05-05", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "1f715dd4-cc8f-4ea3-a099-eabf9e7914ed", active: true, full_name: "Marcus Smith", date_of_birth: "2013-07-29", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "5dab94a3-4bd8-46a8-b7f3-5255e614828e", active: true, full_name: "Sabina Akers", date_of_birth: "2014-08-02", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "f2895d9c-43e2-46c3-9d69-057492868511", active: true, full_name: "Mubiru Karstensen", date_of_birth: "2017-12-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "454aa341-e5e2-441c-90d8-47bce4826c83", active: true, full_name: "Tarquinius Kelly", date_of_birth: "2018-09-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">]

>> @children = kids_active_current.joins(:business).where(businesses: { user: user })
  Child Load (1.0ms)  SELECT "children".* FROM "children" INNER JOIN "child_approvals" ON "child_approvals"."child_id" = "children"."id" INNER JOIN "approvals" ON "approvals"."id" = "child_approvals"."approval_id" INNER JOIN "businesses" ON "businesses"."id" = "children"."business_id" WHERE "children"."active" = $1 AND (effective_on <= '2020-11-11' AND expires_on > '2020-11-11') AND "businesses"."user_id" = $2 LIMIT $3  [["active", true], ["user_id", "6a757758-5182-4fcb-8945-0ae2867cdd78"], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Child id: "454aa341-e5e2-441c-90d8-47bce4826c83", active: true, full_name: "Tarquinius Kelly", date_of_birth: "2018-09-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "f2895d9c-43e2-46c3-9d69-057492868511", active: true, full_name: "Mubiru Karstensen", date_of_birth: "2017-12-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "5dab94a3-4bd8-46a8-b7f3-5255e614828e", active: true, full_name: "Sabina Akers", date_of_birth: "2014-08-02", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "1f715dd4-cc8f-4ea3-a099-eabf9e7914ed", active: true, full_name: "Marcus Smith", date_of_birth: "2013-07-29", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "b17c232e-9da5-499b-891c-56c5f8ee05b0", active: true, full_name: "K'Shawn Henderson", date_of_birth: "2013-05-05", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "1c05c610-09cf-4a52-b16e-af595db735a1", active: true, full_name: "Maria Baca", date_of_birth: "2012-03-21", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">]>

>> @children.each{|kid| puts kid.inspect}
  Child Load (1.1ms)  SELECT "children".* FROM "children" INNER JOIN "child_approvals" ON "child_approvals"."child_id" = "children"."id" INNER JOIN "approvals" ON "approvals"."id" = "child_approvals"."approval_id" INNER JOIN "businesses" ON "businesses"."id" = "children"."business_id" WHERE "children"."active" = $1 AND (effective_on <= '2020-11-11' AND expires_on > '2020-11-11') AND "businesses"."user_id" = $2  [["active", true], ["user_id", "6a757758-5182-4fcb-8945-0ae2867cdd78"]]
#<Child id: "454aa341-e5e2-441c-90d8-47bce4826c83", active: true, full_name: "Tarquinius Kelly", date_of_birth: "2018-09-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "f2895d9c-43e2-46c3-9d69-057492868511", active: true, full_name: "Mubiru Karstensen", date_of_birth: "2017-12-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "5dab94a3-4bd8-46a8-b7f3-5255e614828e", active: true, full_name: "Sabina Akers", date_of_birth: "2014-08-02", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "1f715dd4-cc8f-4ea3-a099-eabf9e7914ed", active: true, full_name: "Marcus Smith", date_of_birth: "2013-07-29", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "b17c232e-9da5-499b-891c-56c5f8ee05b0", active: true, full_name: "K'Shawn Henderson", date_of_birth: "2013-05-05", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
#<Child id: "1c05c610-09cf-4a52-b16e-af595db735a1", active: true, full_name: "Maria Baca", date_of_birth: "2012-03-21", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">
=> [#<Child id: "454aa341-e5e2-441c-90d8-47bce4826c83", active: true, full_name: "Tarquinius Kelly", date_of_birth: "2018-09-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "f2895d9c-43e2-46c3-9d69-057492868511", active: true, full_name: "Mubiru Karstensen", date_of_birth: "2017-12-17", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "5dab94a3-4bd8-46a8-b7f3-5255e614828e", active: true, full_name: "Sabina Akers", date_of_birth: "2014-08-02", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "1f715dd4-cc8f-4ea3-a099-eabf9e7914ed", active: true, full_name: "Marcus Smith", date_of_birth: "2013-07-29", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "b17c232e-9da5-499b-891c-56c5f8ee05b0", active: true, full_name: "K'Shawn Henderson", date_of_birth: "2013-05-05", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">, #<Child id: "1c05c610-09cf-4a52-b16e-af595db735a1", active: true, full_name: "Maria Baca", date_of_birth: "2012-03-21", created_at: "2020-11-11 19:58:08", updated_at: "2020-11-11 19:58:08", business_id: "6323788f-6caf-4953-8c91-4d9bab1ba7b9">]

```
No duplicates at all.

Haven't been able to test the Blueprint query via the console.  (Can't today; maybe you can).

**Comment by katelovescode** [comment]
> Hm. No duplicates for me, even without 'uniq':
> 
> 1. I ran rake db:seed:replant

Right, in my prior comment I said there's nothing in the seeds to give the children more than one approval, this only happens in the spec.  Here's how you can reproduce:

- remove .uniq
- run the spec for the dashboard

You should see failed tests with mismatched numbers of records.

**Comment by katelovescode** [comment]
@weedySeaDragon I paired with a coworker and got this sorted, so no worries!

**Pull request merged**
