### PR TITLE
Add base implementation for Dox

### PR DESCRIPTION
**Pull request by abdulfataiaka**
## 💅🏼 What issue does this fix?

https://github.com/pieforproviders/pieforproviders/issues/1557

## 🛷 Deployment

* [ ] Migrations
* [ ] Dependencies

No migrations but requires `redoc-cli` to be installed locally and the addition of the `dox` gem

## 🧵 Steps to set up locally

Run bundle to install new gems and also install the `redoc-cli`
```

$ yarn install-all

$ bundle

```

Run rake task to generate documentation into `public/api_docs/v1` folder
```

$ rails api_docs:generate

# OR

$ bundle exec rails api_docs:generate

```

Open the documentations in the browser
```

http://localhost:3001/api_docs?format=json&version=v1

http://localhost:3001/api_docs?format=html&version=v1

```

## 🕯 Caveats, concerns

This implementation has not been integrated into the build process, I would recommend we have a separate issue to handle that, to ensure much care is taken to prevent breaking production

### CODE REVIEW

**Review by katelovescode — CHANGES_REQUESTED** [review]
Couple of notes:

You don't have to install the cli globally, instead run:
```
yarn add redoc-cli --dev
```
 and it will add it to the package.json in the root of the project (then commit it so others can use it!)  Anyone who's going to use it will then just need to run `yarn install` from the root.

Also I couldn't get the html view to work:
Screen Shot 2021-11-15 at 3 07 52 PM

**Comment by abdulfataiaka** [comment]
> Couple of notes:
> 
> You don't have to install the cli globally, instead run:
> 
> ```
> yarn add redoc-cli --dev
> ```
> 
> and it will add it to the package.json in the root of the project (then commit it so others can use it!) Anyone who's going to use it will then just need to run `yarn install` from the root.
> 
> Also I couldn't get the html view to work: Screen Shot 2021-11-15 at 3 07 52 PM

Ensure to run the rake task -> `rails api_docs:generate` first

**Comment by abdulfataiaka** [comment]
@katelovescode Comments and suggestions have been addressed

**Comment by katelovescode** [comment]
> Ensure to run the rake task -> `rails api_docs:generate` first

I did before, and I just tried again, and still no HTML view, unfortunately - what command are you running to start your rails server?

I've tried `bundle exec rails s` and `bundle exec rails start` - and in both cases I tried port 3000 and 3001 and no such luck.

What am I missing? 😭

**Comment by abdulfataiaka** [comment]
That's weird, Lets talk more about it after our check-in session today

**Comment by abdulfataiaka** [comment]
I simply do `foreman start` with the API started at the port `3001`. Could it be that your configuration runs the API at a different port?

**Comment by katelovescode** [comment]
We're going to deprioritize this for now.

**Pull request closed without merging**
