### PR TITLE
Move subsidy rule association to a background job

### PR DESCRIPTION
**Pull request by arku**
# 💅🏼 What issue does this fix?

https://github.com/pieforproviders/pieforproviders/issues/561

## 🍂 Before You Submit

* [ ] Did you write tests?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [x] Did you run `bundle exec rspec` from the root?
* [ ] Did you run `bundle exec rails rswag` from the root?
* [x] Did you run `bundle exec rubocop` from the root?
* [ ] Did you run `yarn lint` in `/client`?
* [ ] Did you run `yarn test` in `/client`?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Data Migrations
* [ ] Schema Migrations
* [ ] Dependencies

## 🧳 Steps to test

Run `foreman start` and create a child with a business in IL from from the rails console.

### CODE REVIEW

**Review by katelovescode — CHANGES_REQUESTED** [review]
This is a good start, couple implementation tweaks:
- can we enable the dashboard engine? https://github.com/bensheldon/good_job#execute-jobs-async--in-process
- can we run jobs async with the web server rather than a separate process?  I know Heroku resources get expensive fast: https://github.com/bensheldon/good_job#execute-jobs-async--in-process

**Comment by arku** [comment]
> can we enable the dashboard engine? 

I'm not sure how to do it with our current setup. We only want to allow admin users to access `/good_job`. GoodJob's documentation suggests using Devise's `authenticate` helper to authorize access but we can't use it since we don't use session cookies.

```
authenticate :user, ->(user) { user.admin? } do
  mount GoodJob::Engine => 'good_job'
end
```

How do we go about it?

**Comment by katelovescode** [comment]
> How do we go about it?

Could we write a non-api controller, inherit from GoodJob's dashboards controller, and apply a Pundit policy to it? https://github.com/bensheldon/good_job/blob/main/engine/app/controllers/good_job/dashboards_controller.rb

**Comment by arku** [comment]
> > How do we go about it?
> 
> Could we write a non-api controller, inherit from GoodJob's dashboards controller, and apply a Pundit policy to it? https://github.com/bensheldon/good_job/blob/main/engine/app/controllers/good_job/dashboards_controller.rb

We could do that. This would require us to create another controller + view for login. A simpler solution would be to use basic auth. WDYT?

**Comment by katelovescode** [comment]
> We could do that. This would require us to create another controller + view for login. A simpler solution would be to use basic auth. WDYT?

Personally I'd rather maintain another controller (I think the view will be built in with the good_job gem, we shouldn't have to create one to inherit, as long as the methods use `super`, we should just be able to scope it?  I think?) than a second authentication method.

**Comment by arku** [comment]
> Personally I'd rather maintain another controller (I think the view will be built in with the good_job gem, we shouldn't have to create one to inherit), and in the controller, as long as the methods use super, we should just be able to scope it? I think?

@katelovescode Yeah, that's right about the good job controller. The second controller I was referring to is the `LoginController` to render the login form view. Note that we're already overriding the devise sessions controller and rendering JSON.

**Comment by arku** [comment]
> All of that sounds better than maintaining a second auth structure

I was suggesting basic auth to authorize access as mentioned in https://github.com/bensheldon/good_job#dashboard to keep the code simple for now. If we do want to add new views for login, we can always do it in the future.

**Comment by katelovescode** [comment]
> > Personally I'd rather maintain another controller (I think the view will be built in with the good_job gem, we shouldn't have to create one to inherit), and in the controller, as long as the methods use super, we should just be able to scope it? I think?
> 
> @katelovescode Yeah, that's right about the good job controller. The second controller I was referring to is the `LoginController` to render the login form view. Note that we're already overriding the devise sessions controller and rendering JSON.

Can we co-opt our existing login, though?  Like, can we route to the GoodJob views via React and using the auth token?

**Review by katelovescode — DISMISSED** [review]

**Review by katelovescode — APPROVED** [review]

**Pull request merged**
