### PR TITLE
view attendance tags show billable numbers

### PR DESCRIPTION
**Pull request by twinsfan421**
## 💅🏼 What issue does this fix?
#2431 This would update the tags on the view attendance page to show the calculated amount for both daily and hourly.

## 🍂 Before You Submit

* [x] Did you write & run tests and linters?
* [ ] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [ ] Does your PR contain any required translations?
* [ ] Are your primary keys UUIDs on any new tables?

## 🛷 Deployment

* [ ] Migrations
* [ ] Dependencies

### CODE REVIEW

**Comment by katelovescode** [comment]
Screen Shot 2022-04-12 at 1 57 31 PM
Can we group these tags together as `8.0 hours` and `1.0 days`

**Comment by twinsfan421** [comment]
> Screen Shot 2022-04-12 at 1 57 31 PM
> 
> Can we group these tags together as `8.0 hours` and `1.0 days`

I just sent and update for that

**Comment by katelovescode** [comment]
> > Screen Shot 2022-04-12 at 1 57 31 PM
> > Can we group these tags together as `8.0 hours` and `1.0 days`
> 
> @katelovescode I just sent and update for that but I noticed that since you have ` "daily": "full day", "hourly": "hours",` in the index json, by combining them, it doesn't recognize it and shows up as hourly and daily instead of hours and full day. Would you want me to revert back to how it was and change the front end style or how do you want to handle it?

What I think you're going to want to do is change the backend to return `8.0 hours` and `1.0 full days` (for example) and then split the string and translate it on the front end.  So something like:
```js
/* client/src/AttendanceView/AttendanceView.js:195 */
<div className="flex justify-center">
                {(matchingServiceDay.tags || []).map((tag, i) => (
                  <div
                    key={i}
                    className={`bg-green2 text-green1 box-border p-1 mt-1 ${
                      i > 0 ? 'ml-1' : null
                    }`}
                  >
                    {`${tag.split(' ')[0]} ${t(`${tag.split(' ')[1].toLowerCase()}`)}
                  </div>
                ))}
              </div>```
              
Keeping in mind this is pseudocode concatenating might be a little trickier than that.

Also @rebeccakarasiktw or @cjhaddad - is it okay to change that second tag to `days` instead of `full days`?  Let me know what you think.

**Comment by twinsfan421** [comment]
> > > Screen Shot 2022-04-12 at 1 57 31 PM
> > > Can we group these tags together as `8.0 hours` and `1.0 days`
> > 
> > 
> > @katelovescode I just sent and update for that but I noticed that since you have ` "daily": "full day", "hourly": "hours",` in the index json, by combining them, it doesn't recognize it and shows up as hourly and daily instead of hours and full day. Would you want me to revert back to how it was and change the front end style or how do you want to handle it?
> 
> What I think you're going to want to do is change the backend to return `8.0 hours` and `1.0 full days` (for example) and then split the string and translate it on the front end. So something like:
> 
> ```js
> /* client/src/AttendanceView/AttendanceView.js:195 */
> <div className="flex justify-center">
>                 {(matchingServiceDay.tags || []).map((tag, i) => (
>                   <div
>                     key={i}
>                     className={`bg-green2 text-green1 box-border p-1 mt-1 ${
>                       i > 0 ? 'ml-1' : null
>                     }`}
>                   >
>                     {`${tag.split(' ')[0]} ${t(`${tag.split(' ')[1].toLowerCase()}`)}
>                   </div>
>                 ))}
>               </div>
> ```
> 
> Keeping in mind this is pseudocode, and concatenating might be a little trickier than that.
> 
> Also @rebeccakarasiktw or @cjhaddad - is it okay to change that second tag to `days` instead of `full days`? Let me know what you think.

@katelovescode Ok I just pushed up a fix for that.

**Comment by rebeccakarasiktw** [comment]
Hi @katelovescode I think it would be preferible to keep it as "full day" but can we please take out the ".0" for the "full day" because as I understand it there isn't a way for there to be more than 1, 2, etc full days.

**Comment by twinsfan421** [comment]
> Hi @katelovescode I think it would be preferible to keep it as "full day" but can we please take out the ".0" for the "full day" because as I understand it there isn't a way for there to be more than 1, 2, etc full days.

I just pushed up a commit to remove the ".0" from the full day but can change it back if not preferred.  It would look like this:
Screen Shot 2022-04-13 at 7 43 51 PM

**Comment by katelovescode** [comment]
> > Hi @katelovescode I think it would be preferible to keep it as "full day" but can we please take out the ".0" for the "full day" because as I understand it there isn't a way for there to be more than 1, 2, etc full days.
> 
> I just pushed up a commit to remove the ".0" from the full day but can change it back if not preferred. It would look like this: Screen Shot 2022-04-13 at 7 43 51 PM

The good news is, this will never need to say "2 full days" in NE because they top it at 18 hours :) Looks great, thanks for the speedy turnaround!

**Review by katelovescode — APPROVED** [review]

**Pull request merged**
