### PR TITLE
Update error page

### PR DESCRIPTION
**Pull request by nneka-nu**
# 💅🏼 What issue does this fix?

#985
## 🍂 Before You Submit

* [x] Did you write tests?
* [x] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [x] Does your PR contain any required translations?
* [ ] Did you run `bundle exec rspec` from the root?
* [ ] Did you run `bundle exec rails rswag` from the root?
* [ ] Did you run `bundle exec rubocop` from the root?
* [x] Did you run `yarn lint` in `/client`?
* [x] Did you run `yarn test` in `/client`?
* [ ] Are your primary keys UUIDs on any new tables?

## 🕯 Caveats, concerns

I had to move the header from LoggedInLayout to its own component so I could use it in the error page.

### CODE REVIEW

**Comment by cjhaddad** [comment]
Hi @nneka-nu can you make sure to tag me as a reviewer when you make PRs for the frontend? Thank you!

**Comment by nneka-nu** [comment]
Hi, @cjhaddad. 
GitHub doesn’t give me the option to request a review. Kate is automatically added.
I believe it’s because I wasn’t added to the repo as a collaborator, and I’m using a forked repo.

**Comment by katelovescode** [comment]
> Hi, @cjhaddad.
> GitHub doesn’t give me the option to request a review. Kate is automatically added.
> I believe it’s because I wasn’t added to the repo as a collaborator, and I’m using a forked repo.

@cjhaddad I'll fix this so we both automatically get tagged.

**Comment by katelovescode** [comment]
@nneka-nu please rebase this branch off of develop and your specs should pass!

**Comment by nneka-nu** [comment]
@cjhaddad, I don't know why the Cypress test failed. I did not modify any Cypress files.

**Comment by katelovescode** [comment]
> @cjhaddad, I don't know why the Cypress test failed. I did not modify any Cypress files.

It's probably just flakey, I'll re-run them after I make a ticket for the flakey one.

**Comment by nneka-nu** [comment]
Okay. Good to know.

**Comment by katelovescode** [comment]
@nneka-nu Tests are passing now; if you need to make more changes and they flake out again, you or @cjhaddad can push "rerun all jobs" in the checks

**Review by cjhaddad — APPROVED** [review]

**Pull request merged**
